import { StyleSheet } from 'react-native';

export const eventsStyles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 16,
        backgroundColor: '#fff',
    },
    scrollView: {
        flex: 1,
    },
    header: {
        marginBottom: 20,
        marginTop: 30,
        alignItems: 'center',
    },
    title: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#333',
        marginVertical: 10,
        textAlign: 'center',
    },
    subtitle: {
        fontSize: 18,
        color: '#666',
        marginBottom: 10,
        textAlign: 'center',
    },
    calendarContainer: {
        marginBottom: 20,
        height: 400,
        borderRadius: 10,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: '#e0e0e0',
    },
    calendar: {
        flex: 1,
        backgroundColor: '#fff',
    },
    calendarToggleButton: {
        backgroundColor: '#FF9843',
        borderRadius: 8,
        padding: 12,
        alignItems: 'center',
        marginBottom: 15,
        flexDirection: 'row',
        justifyContent: 'center',
    },
    calendarToggleText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    sectionTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 15,
        marginTop: 10,
    },
    eventCard: {
        backgroundColor: '#fff',
        borderRadius: 10,
        padding: 16,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    holidayCard: {
        backgroundColor: '#FFF9F0',
        borderRadius: 10,
        padding: 16,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
        borderLeftWidth: 4,
        borderLeftColor: '#FF9843',
    },
    holidayTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 5,
    },
    holidayDate: {
        fontSize: 14,
        color: '#666',
        marginBottom: 8,
    },
    holidayTag: {
        backgroundColor: '#FF9843',
        borderRadius: 4,
        paddingHorizontal: 8,
        paddingVertical: 4,
        alignSelf: 'flex-start',
        marginBottom: 8,
    },
    holidayTagText: {
        color: '#fff',
        fontSize: 12,
        fontWeight: 'bold',
    },
    eventHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 10,
    },
    eventTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 5,
        flex: 1,
    },
    recurringTag: {
        fontSize: 14,
        fontWeight: 'normal',
        color: '#FF9843',
        fontStyle: 'italic',
    },
    dateContainer: {
        backgroundColor: '#FFE4C4',
        borderRadius: 5,
        padding: 8,
        alignItems: 'center',
        justifyContent: 'center',
        minWidth: 60,
    },
    dateText: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#FF9843',
    },
    eventDate: {
        fontSize: 14,
        color: '#666',
        marginBottom: 8,
    },
    eventLocation: {
        fontSize: 14,
        color: '#666',
        marginBottom: 8,
    },
    eventDescription: {
        fontSize: 15,
        color: '#555',
        lineHeight: 22,
        marginBottom: 12,
    },
    eventImage: {
        width: '100%',
        height: 160,
        borderRadius: 8,
        marginVertical: 10,
    },
    buttonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 10,
    },
    detailsButton: {
        backgroundColor: '#FF9843',
        borderRadius: 8,
        padding: 10,
        alignItems: 'center',
        flex: 1,
        marginRight: 5,
    },
    registerButton: {
        backgroundColor: '#4CAF50',
        borderRadius: 8,
        padding: 10,
        alignItems: 'center',
        flex: 1,
        marginLeft: 5,
    },
    buttonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: 'bold',
    },
    divider: {
        height: 1,
        backgroundColor: '#e0e0e0',
        marginVertical: 10,
    },
    modalContainer: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        backgroundColor: '#fff',
        borderRadius: 10,
        padding: 20,
        width: '90%',
        maxHeight: '80%',
    },
    modalTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 15,
    },
    closeButton: {
        position: 'absolute',
        top: 10,
        right: 10,
        padding: 5,
    },
    modalScrollView: {
        marginBottom: 10,
    },
    pastEventCard: {
        backgroundColor: '#f5f5f5',
        opacity: 0.8,
    },
    pastEventBadge: {
        position: 'absolute',
        top: 10,
        right: 10,
        backgroundColor: '#999',
        borderRadius: 4,
        padding: 4,
        zIndex: 1,
    },
    pastEventText: {
        color: '#fff',
        fontSize: 12,
        fontWeight: 'bold',
    },
    noEventsContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
    },
    noEventsText: {
        fontSize: 16,
        color: '#666',
        textAlign: 'center',
    },
    errorText: {
        fontSize: 14,
        color: '#FF3B30',
        textAlign: 'center',
        marginVertical: 10,
    },
    tabContainer: {
        flexDirection: 'row',
        marginBottom: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
    },
    tab: {
        flex: 1,
        paddingVertical: 10,
        alignItems: 'center',
    },
    activeTab: {
        borderBottomWidth: 2,
        borderBottomColor: '#FF9843',
    },
    tabText: {
        fontSize: 16,
        color: '#666',
    },
    activeTabText: {
        color: '#FF9843',
        fontWeight: 'bold',
    },
    // Month group styles
    monthGroup: {
        marginBottom: 20,
    },
    monthTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#2C3E50',
        marginBottom: 10,
        paddingHorizontal: 5,
        paddingVertical: 8,
        backgroundColor: '#f8f9fa',
        borderRadius: 5,
        borderLeftWidth: 3,
        borderLeftColor: '#FF9843',
    },
    refreshButton: {
        backgroundColor: '#FF9843',
        borderRadius: 8,
        padding: 12,
        alignItems: 'center',
        marginTop: 15,
        marginBottom: 20,
        flexDirection: 'row',
        justifyContent: 'center',
    },
    // Month navigation
    monthNavigation: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginVertical: 15,
        paddingHorizontal: 10,
    },
    monthNavigationButton: {
        padding: 10,
        borderRadius: 8,
        backgroundColor: '#f8f9fa',
    },
    monthNavigationDisabled: {
        opacity: 0.5,
    },
    currentMonthDisplay: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
    },
    yearPickerButton: {
        padding: 8,
        borderRadius: 8,
        backgroundColor: '#FFE4C4',
        marginBottom: 15,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    yearPickerText: {
        fontSize: 16,
        color: '#333',
        fontWeight: '600',
    },
    paginationContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginVertical: 15,
    },
    paginationDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#E0E0E0',
        marginHorizontal: 5,
    },
    paginationDotActive: {
        backgroundColor: '#FF9843',
        width: 10,
        height: 10,
        borderRadius: 5,
    },
    monthPicker: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        marginVertical: 10,
        padding: 10,
        backgroundColor: '#f8f9fa',
        borderRadius: 10,
    },
    monthPickerItem: {
        width: '30%',
        paddingVertical: 10,
        paddingHorizontal: 5,
        alignItems: 'center',
        marginBottom: 10,
        borderRadius: 8,
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#E0E0E0',
    },
    monthPickerItemActive: {
        backgroundColor: '#FFE4C4',
        borderColor: '#FF9843',
    },
    monthPickerText: {
        fontSize: 14,
        color: '#666',
    },
    monthPickerTextActive: {
        fontWeight: 'bold',
        color: '#FF9843',
    },
});