import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

/**
 * Creates themed styles for the HomeContent component
 */
export const createHomeStyles = (colors: any) => StyleSheet.create({
    container: {
        flex: 1,
        padding: 16,
        backgroundColor: colors.background,
    },
    scrollView: {
        flex: 1,
    },
    scrollViewContent: {
        paddingBottom: 20,
    },
    heroSection: {
        marginBottom: 24,
        marginTop: 30,
        alignItems: 'center',
        paddingHorizontal: 10,
    },
    header: {
        marginBottom: 24,
        marginTop: 30,
        alignItems: 'center',
        paddingVertical: 20,
        paddingHorizontal: 16,
        backgroundColor: colors.card,
        borderRadius: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
        borderColor: colors.border,
        borderWidth: 1,
    },
    headerDivider: {
        height: 1,
        width: '40%',
        backgroundColor: colors.border,
        marginVertical: 10,
        opacity: 0.7,
    },
    logo: {
        width: 50,
        height: 50,
        resizeMode: 'contain',
    },
    title: {
        fontSize: 28,
        fontWeight: 'bold',
        color: colors.text,
        marginTop: 10,
        marginBottom: 5,
        textAlign: 'center',
    },
    subtitle: {
        fontSize: 18,
        color: colors.text,
        opacity: 0.7,
        marginBottom: 20,
        textAlign: 'center',
    },
    featureGridContainer: {
        marginBottom: 24,
    },
    featureRow: {
        justifyContent: 'space-between',
        marginBottom: 16,
    },
    featureCard: {
        width: '48%',
        backgroundColor: colors.card,
        borderRadius: 12,
        padding: 16,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        borderColor: colors.border,
        borderWidth: 1,
    },
    featureIconContainer: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: colors.background,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 12,
        borderWidth: 1,
        borderColor: colors.border,
    },
    featureTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: colors.text,
        textAlign: 'center',
    },
    cardContainer: {
        backgroundColor: colors.card,
        borderRadius: 12,
        padding: 18,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
        borderColor: colors.border,
        borderWidth: 1,
    },
    streamCardContainer: {
        backgroundColor: colors.card,
        borderRadius: 12,
        padding: 18,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        borderColor: colors.border,
        borderWidth: 1,
    },
    sectionHeaderRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: 12,
    },
    sectionHeaderIcon: {
        marginRight: 10,
        marginTop: 2,
        flexShrink: 0,
    },
    sectionTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        color: colors.text,
        marginBottom: 15,
        flex: 1,
    },
    infoText: {
        fontSize: 16,
        color: colors.text,
        opacity: 0.8,
        lineHeight: 24,
        marginBottom: 12,
    },
    videoContainer: {
        marginTop: 15,
        width: '100%',
        height: 200,
        borderRadius: 12,
        overflow: 'hidden',
        backgroundColor: '#000',
    },
    videoWebView: {
        flex: 1,
        backgroundColor: '#000',
    },
    image: {
        width: '100%',
        height: 200,
        borderRadius: 8,
        marginTop: 10,
        marginBottom: 15,
    },
    button: {
        backgroundColor: colors.primary,
        borderRadius: 8,
        padding: 12,
        alignItems: 'center',
        marginTop: 10,
    },
    buttonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    divider: {
        height: 1,
        backgroundColor: colors.border,
        marginVertical: 15,
    },
    serviceItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
    },
    serviceTime: {
        fontSize: 16,
        fontWeight: 'bold',
        marginRight: 10,
        color: colors.text,
    },
    serviceDesc: {
        fontSize: 16,
        color: colors.text,
        opacity: 0.8,
    },
    contactRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
    },
    contactIcon: {
        width: 24,
        marginRight: 10,
    },
    loadingContainer: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    errorText: {
        fontSize: 16,
        color: '#FF3B30',
    },
    retryButton: {
        marginTop: 20,
        padding: 10,
        backgroundColor: colors.primary,
        borderRadius: 8,
    },
    retryButtonText: {
        color: '#FFFFFF',
    },
    subsectionContainer: {
        marginBottom: 20,
    },
    subsectionTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.text,
        marginBottom: 10,
        flexShrink: 1,
        flexWrap: 'wrap',
    },
    itemRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: 8,
        paddingRight: 10,
    },
    itemIcon: {
        marginRight: 8,
        marginTop: 2,
        flexShrink: 0,
    },
    skeletonContainer: {
        backgroundColor: colors.card,
    },
    skeletonBox: {
        backgroundColor: colors.border,
        borderRadius: 4,
        opacity: 0.15,
    },
    skeletonCircle: {
        backgroundColor: colors.border,
        borderRadius: 100,
        opacity: 0.15,
    },
});

/**
 * Creates themed styles for the WhoWeAre component
 */
export const createWhoWeAreStyles = (colors: any) => StyleSheet.create({
    container: {
        flex: 1,
        padding: 16,
        backgroundColor: colors.background,
    },
    scrollView: {
        flex: 1,
    },
    scrollViewContent: {
        paddingBottom: 30,
    },
    header: {
        marginBottom: 24,
        marginTop: 30,
        alignItems: 'center',
        paddingVertical: 20,
        paddingHorizontal: 16,
        backgroundColor: colors.card,
        borderRadius: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
        borderColor: colors.border,
        borderWidth: 1,
    },
    headerDivider: {
        height: 1,
        width: '40%',
        backgroundColor: colors.border,
        marginVertical: 10,
        opacity: 0.7,
    },
    title: {
        fontSize: 28,
        fontWeight: 'bold',
        color: colors.text,
        marginVertical: 10,
        textAlign: 'center',
    },
    subtitle: {
        fontSize: 18,
        color: colors.text,
        opacity: 0.7,
        marginBottom: 10,
        textAlign: 'center',
    },
    sectionContainer: {
        backgroundColor: colors.card,
        borderRadius: 12,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        borderColor: colors.border,
        borderWidth: 1,
        overflow: 'hidden',
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 16,
    },
    sectionHeaderContent: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    sectionIconContainer: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: colors.text,
    },
    paragraph: {
        fontSize: 16,
        color: colors.text,
        opacity: 0.8,
        lineHeight: 24,
        marginBottom: 15,
        paddingHorizontal: 16,
        paddingBottom: 16,
    },
    valueItem: {
        marginBottom: 12,
        paddingHorizontal: 16,
    },
    valueText: {
        fontSize: 16,
        color: colors.text,
        fontWeight: '500',
    },
    teamGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-around',
        padding: 10,
    },
    teamMemberCard: {
        width: (width - 80) / 2,
        backgroundColor: colors.background,
        borderRadius: 12,
        padding: 12,
        marginBottom: 16,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 2,
        borderColor: colors.border,
        borderWidth: 1,
    },
    teamMemberImage: {
        width: 100,
        height: 100,
        borderRadius: 50,
        marginBottom: 12,
        borderWidth: 3,
        borderColor: colors.primary,
    },
    teamMemberInfo: {
        alignItems: 'center',
    },
    teamMemberName: {
        fontSize: 16,
        fontWeight: 'bold',
        color: colors.text,
        textAlign: 'center',
    },
    teamMemberLastName: {
        fontSize: 14,
        color: colors.text,
        opacity: 0.7,
        textAlign: 'center',
    },
    downloadButton: {
        backgroundColor: colors.primary,
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 25,
        marginTop: 15,
        marginBottom: 10,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        alignSelf: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
        elevation: 3,
    },
    downloadButtonText: {
        color: '#FFFFFF',
        fontSize: 15,
        fontWeight: '600',
        textAlign: 'center',
    },
});

/**
 * Creates themed styles for the EventsContent component
 */
export const createEventsStyles = (colors: any) => StyleSheet.create({
    container: {
        flex: 1,
        padding: 16,
        backgroundColor: colors.background,
    },
    scrollView: {
        flex: 1,
    },
    header: {
        marginBottom: 24,
        marginTop: 30,
        alignItems: 'center',
        paddingVertical: 20,
        paddingHorizontal: 16,
        backgroundColor: colors.card,
        borderRadius: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
        borderColor: colors.border,
        borderWidth: 1,
    },
    headerDivider: {
        height: 1,
        width: '40%',
        backgroundColor: colors.border,
        marginVertical: 10,
        opacity: 0.7,
    },
    title: {
        fontSize: 28,
        fontWeight: 'bold',
        color: colors.text,
        marginVertical: 10,
        textAlign: 'center',
    },
    subtitle: {
        fontSize: 18,
        color: colors.text,
        opacity: 0.7,
        marginBottom: 10,
        textAlign: 'center',
    },
    calendarContainer: {
        marginBottom: 20,
        height: 400,
        borderRadius: 10,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: colors.border,
    },
    calendar: {
        flex: 1,
        backgroundColor: colors.card,
    },
    tabContainer: {
        flexDirection: 'row',
        marginVertical: 15,
        borderRadius: 8,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: colors.border,
    },
    tab: {
        flex: 1,
        paddingVertical: 12,
        alignItems: 'center',
        backgroundColor: colors.card,
    },
    activeTab: {
        backgroundColor: colors.primary,
    },
    tabText: {
        fontSize: 14,
        fontWeight: '500',
        color: colors.text,
    },
    activeTabText: {
        color: '#FFFFFF',
    },
    sectionTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        color: colors.text,
        marginBottom: 15,
        marginTop: 10,
    },
    monthNavigation: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginVertical: 15,
    },
    monthNavigationButton: {
        padding: 8,
        borderRadius: 20,
        backgroundColor: colors.card,
    },
    yearPickerButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 20,
        backgroundColor: colors.card,
    },
    currentMonthDisplay: {
        fontSize: 16,
        fontWeight: 'bold',
        color: colors.text,
    },
    monthPicker: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        backgroundColor: colors.card,
        borderRadius: 8,
        padding: 12,
        marginBottom: 15,
    },
    monthPickerItem: {
        width: '30%',
        paddingVertical: 8,
        marginVertical: 4,
        alignItems: 'center',
        borderRadius: 4,
    },
    monthPickerItemActive: {
        backgroundColor: colors.primary,
    },
    monthPickerText: {
        fontSize: 14,
        color: colors.text,
    },
    monthPickerTextActive: {
        color: '#FFFFFF',
        fontWeight: 'bold',
    },
    eventCard: {
        backgroundColor: colors.card,
        borderRadius: 10,
        padding: 16,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
        borderColor: colors.border,
        borderWidth: 1,
    },
    eventHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 10,
    },
    eventTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: colors.text,
        marginBottom: 5,
        flex: 1,
    },
    recurringTag: {
        fontSize: 14,
        fontWeight: 'normal',
        color: colors.primary,
        fontStyle: 'italic',
    },
    dateContainer: {
        backgroundColor: colors.accent,
        borderRadius: 5,
        padding: 8,
        alignItems: 'center',
        justifyContent: 'center',
        minWidth: 60,
    },
    dateText: {
        fontSize: 14,
        fontWeight: 'bold',
        color: colors.primary,
    },
    eventDate: {
        fontSize: 14,
        color: colors.text,
        opacity: 0.7,
        marginBottom: 8,
    },
    eventLocation: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    eventLocationText: {
        fontSize: 14,
        color: colors.text,
        opacity: 0.7,
        marginLeft: 5,
        textDecorationLine: 'underline',
    },
    eventDescription: {
        fontSize: 15,
        color: colors.text,
        opacity: 0.8,
        lineHeight: 22,
        marginBottom: 12,
    },
    descriptionContainer: {
        marginVertical: 10,
    },
    readMoreButton: {
        alignSelf: 'flex-end',
        marginTop: 4,
    },
    readMoreText: {
        fontSize: 14,
        color: colors.primary,
        fontWeight: '500',
    },
    attachmentsContainer: {
        marginTop: 10,
        marginBottom: 8,
    },
    attachmentsTitle: {
        fontSize: 14,
        fontWeight: 'bold',
        color: colors.text,
        opacity: 0.7,
        marginBottom: 5,
    },
    attachmentItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 3,
    },
    attachmentText: {
        fontSize: 14,
        color: colors.primary,
        marginLeft: 8,
        textDecorationLine: 'underline',
    },
    buttonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 10,
    },
    detailsButton: {
        backgroundColor: colors.primary,
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderRadius: 8,
        alignItems: 'center',
        flex: 1,
        marginRight: 5,
    },
    registerButton: {
        backgroundColor: colors.primary,
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderRadius: 8,
        alignItems: 'center',
        flex: 1,
        marginLeft: 5,
    },
    buttonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    additionalButtonsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 8,
    },
    secondaryButton: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 8,
        backgroundColor: colors.accent,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: colors.border,
        flex: 1,
        justifyContent: 'center',
        marginHorizontal: 2,
    },
    secondaryButtonText: {
        fontSize: 12,
        color: colors.primary,
        fontWeight: '500',
    },
    refreshButton: {
        backgroundColor: colors.primary,
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderRadius: 8,
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
        marginVertical: 10,
    },
    holidayCard: {
        backgroundColor: colors.accent,
        borderRadius: 10,
        padding: 16,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
        borderLeftWidth: 4,
        borderLeftColor: colors.primary,
    },
    holidayTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: colors.text,
        marginBottom: 5,
    },
    holidayDate: {
        fontSize: 14,
        color: colors.text,
        opacity: 0.7,
        marginBottom: 8,
    },
    holidayTag: {
        backgroundColor: colors.primary,
        borderRadius: 4,
        paddingHorizontal: 8,
        paddingVertical: 4,
        alignSelf: 'flex-start',
        marginBottom: 8,
    },
    holidayTagText: {
        color: '#fff',
        fontSize: 12,
        fontWeight: 'bold',
    },
    descriptionModal: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1000,
    },
    descriptionModalContent: {
        backgroundColor: colors.card,
        borderRadius: 12,
        width: '87%',
        padding: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 4,
        borderWidth: 1,
        borderColor: colors.border,
    },
    descriptionModalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
        paddingBottom: 8,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    descriptionModalTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: colors.text,
        flex: 1,
        marginRight: 8,
    },
    modalCloseIconButton: {
        padding: 4,
        backgroundColor: colors.background,
        borderRadius: 12,
        height: 24,
        width: 24,
        alignItems: 'center',
        justifyContent: 'center',
    },
    descriptionModalScrollView: {
        maxHeight: 220,
    },
    modalEventDate: {
        fontSize: 12,
        color: colors.primary,
        marginBottom: 6,
        fontWeight: '500',
    },
    descriptionModalText: {
        fontSize: 16,
        color: colors.text,
        lineHeight: 20,
        marginBottom: 8,
    },
    modalPhotoAttachmentsContainer: {
        marginTop: 6,
        padding: 6,
        backgroundColor: colors.background,
        borderRadius: 6,
        marginBottom: 6,
    },
    modalAttachmentsTitle: {
        fontSize: 12,
        fontWeight: '600',
        color: colors.text,
        marginBottom: 4,
    },
    modalPhotoItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 4,
        borderBottomWidth: 1,
        borderBottomColor: colors.border + '30',
    },
    modalAttachmentText: {
        fontSize: 12,
        marginLeft: 4,
        flex: 1,
    },
    modalButtonsContainer: {
        marginTop: 20,
        flexDirection: 'column',
        width: '100%',
    },
    modalButtonsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
    },
    modalActionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 8,
        borderRadius: 6,
    },
    noEventsContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
        backgroundColor: colors.card,
        borderRadius: 8,
        marginVertical: 10,
    },
    noEventsText: {
        fontSize: 16,
        color: colors.text,
        opacity: 0.7,
        textAlign: 'center',
        marginVertical: 15,
    },
    errorText: {
        fontSize: 16,
        color: '#FF3B30',
    },
    loadingContainer: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    viewModeContainer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: colors.card,
        borderRadius: 8,
        marginHorizontal: 16,
        marginBottom: 16,
    },
    viewModeButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 6,
        backgroundColor: 'transparent',
    },
    activeViewModeButton: {
        backgroundColor: colors.primary,
    },
    viewModeText: {
        fontSize: 14,
        color: colors.text,
        marginLeft: 4,
    },
    activeViewModeText: {
        color: '#FFFFFF',
        fontWeight: '600',
    },
    filterButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.card,
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 6,
        marginHorizontal: 16,
        marginBottom: 16,
        alignSelf: 'flex-start',
    },
    filterButtonText: {
        fontSize: 14,
        color: colors.text,
        marginLeft: 4,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    filterModalContent: {
        backgroundColor: colors.background,
        borderRadius: 12,
        padding: 20,
        width: '80%',
        maxWidth: 400,
    },
    filterModalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    filterModalTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: colors.text,
    },
    filterOptions: {
        gap: 12,
    },
    filterOption: {
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 8,
        backgroundColor: colors.card,
    },
    activeFilterOption: {
        backgroundColor: colors.primary,
    },
    filterOptionText: {
        fontSize: 16,
        color: colors.text,
    },
    activeFilterOptionText: {
        color: '#FFFFFF',
        fontWeight: '600',
    },
    timelineContainer: {
        padding: 16,
    },
    timelineGroup: {
        marginBottom: 24,
    },
    timelineDate: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.text,
        marginBottom: 12,
        paddingHorizontal: 16,
    },
    listContainer: {
        padding: 16,
    },
    button: {
        backgroundColor: colors.primary,
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 8,
        alignItems: 'center',
        marginTop: 10,
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.card,
        borderRadius: 8,
        paddingHorizontal: 12,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: colors.border,
    },
    searchIcon: {
        marginRight: 8,
    },
    searchInput: {
        flex: 1,
        height: 40,
        color: colors.text,
        fontSize: 16,
    },
    filterSectionTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.text,
        marginBottom: 12,
        marginTop: 16,
    },
    sortOptions: {
        marginTop: 8,
    },
    sortRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    sortLabel: {
        fontSize: 14,
        color: colors.text,
        marginRight: 12,
        width: 70,
    },
    sortButtons: {
        flexDirection: 'row',
        flex: 1,
        gap: 8,
    },
    sortButton: {
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 6,
        backgroundColor: colors.card,
        borderWidth: 1,
        borderColor: colors.border,
    },
    activeSortButton: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
    },
    sortButtonText: {
        fontSize: 14,
        color: colors.text,
    },
    activeSortButtonText: {
        color: '#FFFFFF',
        fontWeight: '600',
    },
    applyButton: {
        backgroundColor: colors.primary,
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 8,
        alignItems: 'center',
        marginTop: 24,
    },
    applyButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
    },
    featuredContainer: {
        padding: 16,
    },
    featuredSection: {
        marginBottom: 24,
    },
    featuredHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
        paddingBottom: 8,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    featuredTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: colors.text,
        marginLeft: 8,
    },
    featuredEventCard: {
        backgroundColor: colors.card,
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
        borderColor: colors.border,
        borderWidth: 1,
    },
    featuredEventHeader: {
        flexDirection: 'row',
        marginBottom: 12,
    },
    featuredDateContainer: {
        width: 60,
        height: 60,
        backgroundColor: colors.primary,
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    featuredDateDay: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#FFFFFF',
    },
    featuredDateMonth: {
        fontSize: 14,
        color: '#FFFFFF',
        textTransform: 'uppercase',
    },
    featuredEventInfo: {
        flex: 1,
    },
    featuredEventTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.text,
        marginBottom: 4,
    },
    featuredEventTime: {
        fontSize: 14,
        color: colors.text,
        opacity: 0.7,
        marginBottom: 4,
    },
    featuredEventLocation: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    featuredEventLocationText: {
        fontSize: 14,
        color: colors.text,
        opacity: 0.7,
        marginLeft: 4,
    },
    featuredEventActions: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 12,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: colors.border,
    },
    featuredActionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 6,
        backgroundColor: colors.accent,
    },
    featuredActionText: {
        fontSize: 14,
        color: colors.primary,
        marginLeft: 4,
    },
    periodSelectorContainer: {
        marginBottom: 16,
        backgroundColor: colors.card,
        borderRadius: 12,
        padding: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
        borderColor: colors.border,
        borderWidth: 1,
    },
    periodTypeSelector: {
        flexDirection: 'row',
        marginBottom: 12,
        backgroundColor: colors.background,
        borderRadius: 8,
        padding: 4,
    },
    periodTypeButton: {
        flex: 1,
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 6,
        alignItems: 'center',
    },
    activePeriodTypeButton: {
        backgroundColor: colors.primary,
    },
    periodTypeText: {
        fontSize: 14,
        color: colors.text,
        fontWeight: '500',
    },
    activePeriodTypeText: {
        color: '#FFFFFF',
        fontWeight: '600',
    },
    quickPeriodSelector: {
        flexDirection: 'row',
        marginTop: 8,
    },
    quickPeriodButton: {
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 16,
        backgroundColor: colors.background,
        marginRight: 8,
        borderWidth: 1,
        borderColor: colors.border,
    },
    activeQuickPeriodButton: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
    },
    quickPeriodText: {
        fontSize: 13,
        color: colors.text,
    },
    activeQuickPeriodText: {
        color: '#FFFFFF',
        fontWeight: '600',
    },
    monthSelector: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: 8,
    },
    currentMonthButton: {
        flex: 1,
        alignItems: 'center',
        paddingVertical: 8,
    },
    currentMonthText: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.text,
    },
    monthPickerModal: {
        backgroundColor: colors.card,
        borderRadius: 12,
        padding: 20,
        width: '90%',
        maxHeight: '80%',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    monthPickerHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 15,
        paddingBottom: 15,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    monthPickerTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: colors.text,
    },
    closeButton: {
        padding: 8,
    },
});

/**
 * Creates themed styles for the GetConnectedContent component
 */
export const createGetConnectedStyles = (colors: any) => StyleSheet.create({
    container: {
        flex: 1,
        padding: 16,
        backgroundColor: colors.background,
    },
    scrollView: {
        flex: 1,
    },
    scrollViewContent: {
        paddingBottom: 30,
    },
    header: {
        marginBottom: 24,
        marginTop: 30,
        alignItems: 'center',
        paddingVertical: 20,
        paddingHorizontal: 16,
        backgroundColor: colors.card,
        borderRadius: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
        borderColor: colors.border,
        borderWidth: 1,
    },
    headerDivider: {
        height: 1,
        width: '40%',
        backgroundColor: colors.border,
        marginVertical: 10,
        opacity: 0.7,
    },
    title: {
        fontSize: 28,
        fontWeight: 'bold',
        color: colors.text,
        marginVertical: 10,
        textAlign: 'center',
    },
    subtitle: {
        fontSize: 18,
        color: colors.text,
        opacity: 0.7,
        marginBottom: 10,
        textAlign: 'center',
    },
    sectionsContainer: {
        marginTop: 10,
    },
    sectionCard: {
        backgroundColor: colors.card,
        borderRadius: 12,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        borderColor: colors.border,
        borderWidth: 1,
        overflow: 'hidden',
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        backgroundColor: colors.card,
    },
    sectionIconContainer: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: colors.text,
        flex: 1,
    },
    expandIcon: {
        marginLeft: 10,
    },
    paragraph: {
        fontSize: 16,
        color: colors.text,
        opacity: 0.8,
        lineHeight: 24,
        marginBottom: 16,
        paddingHorizontal: 16,
    },
    actionButton: {
        backgroundColor: colors.primary,
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 25,
        marginHorizontal: 16,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
        elevation: 3,
    },
    buttonContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    buttonText: {
        color: '#FFFFFF',
        fontSize: 15,
        fontWeight: '600',
        textAlign: 'center',
    },
    contactsContainer: {
        paddingHorizontal: 16,
        paddingBottom: 16,
    },
    contactButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'transparent',
        paddingVertical: 12,
        marginBottom: 10,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: colors.border,
        paddingHorizontal: 16,
    },
    contactIconContainer: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    contactButtonText: {
        fontSize: 15,
        color: colors.text,
        fontWeight: '500',
    },
    dualButtonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingBottom: 16,
    },
    dualButton: {
        flex: 1,
        backgroundColor: colors.primary,
        paddingVertical: 12,
        paddingHorizontal: 10,
        borderRadius: 25,
        marginHorizontal: 5,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
        elevation: 3,
    },
    cardContainer: {
        backgroundColor: colors.card,
        borderRadius: 10,
        padding: 16,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
        borderColor: colors.border,
        borderWidth: 1,
    },
    primaryButton: {
        backgroundColor: colors.primary,
        paddingVertical: 12,
        paddingHorizontal: 15,
        borderRadius: 8,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 10,
    },
    loadingContainer: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    errorText: {
        fontSize: 16,
        color: '#FF3B30',
    },
    retryButton: {
        marginTop: 20,
        padding: 10,
        backgroundColor: colors.primary,
        borderRadius: 8,
    },
    retryButtonText: {
        color: '#FFFFFF',
    },
});

/**
 * Creates themed styles for the DonationContent component
 */
export const createDonationStyles = (colors: any) => StyleSheet.create({
    container: {
        flex: 1,
        padding: 16,
        backgroundColor: colors.background,
    },
    scrollView: {
        flex: 1,
    },
    header: {
        marginBottom: 24,
        marginTop: 30,
        alignItems: 'center',
        paddingVertical: 20,
        paddingHorizontal: 16,
        backgroundColor: colors.card,
        borderRadius: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
        borderColor: colors.border,
        borderWidth: 1,
    },
    headerDivider: {
        height: 1,
        width: '40%',
        backgroundColor: colors.border,
        marginVertical: 10,
        opacity: 0.7,
    },
    title: {
        fontSize: 28,
        fontWeight: 'bold',
        color: colors.text,
        marginVertical: 10,
        textAlign: 'center',
    },
    subtitle: {
        fontSize: 18,
        color: colors.text,
        opacity: 0.7,
        marginBottom: 5,
        textAlign: 'center',
    },
    cardContainer: {
        backgroundColor: colors.card,
        borderRadius: 10,
        padding: 16,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
        borderColor: colors.border,
        borderWidth: 1,
    },
    cardHeader: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: 16,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
        flexWrap: 'wrap',
    },
    cardHeaderIcon: {
        marginRight: 12,
        marginTop: 4,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: colors.text,
        marginBottom: 15,
        flex: 1,
        flexWrap: 'wrap',
    },
    paragraph: {
        fontSize: 16,
        color: colors.text,
        opacity: 0.8,
        lineHeight: 24,
        marginBottom: 15,
    },
    donationButtonsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 15,
        gap: 10,
    },
    donationButton: {
        backgroundColor: colors.primary,
        paddingVertical: 16,
        paddingHorizontal: 12,
        borderRadius: 12,
        flex: 1,
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3,
        minHeight: 100,
    },
    buttonIcon: {
        marginBottom: 10,
    },
    buttonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: 'bold',
        textAlign: 'center',
        flexWrap: 'wrap',
    },
    bankDetailsContainer: {
        marginTop: 16,
        backgroundColor: colors.card,
        padding: 18,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.border,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 2,
    },
    bankDetailRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
        paddingHorizontal: 4,
    },
    bankDetailLabel: {
        fontSize: 14,
        color: colors.text,
        fontWeight: '500',
        opacity: 0.8,
        flex: 1,
        marginRight: 10,
    },
    bankDetailValueContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    bankDetailValue: {
        fontSize: 14,
        color: colors.primary,
        fontWeight: '600',
        marginRight: 8,
        textAlign: 'right',
    },
    donateNowContainer: {
        paddingHorizontal: 16,
        paddingVertical: 24,
        marginTop: 8,
        marginBottom: 16,
    },
    donateNowButton: {
        backgroundColor: colors.primary,
        paddingVertical: 18,
        borderRadius: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.35,
        shadowRadius: 4,
    },
    donateNowButtonText: {
        color: '#fff',
        fontSize: 20,
        fontWeight: 'bold',
    },
});