import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

/**
 * Creates themed styles for the HomeContent component
 */
export const createHomeStyles = (colors: any) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.background,
    },
    scrollView: {
        flex: 1,
    },
    scrollViewContent: {
        paddingBottom: 20,
    },
    heroSection: {
        height: 200,
        backgroundColor: colors.primary,
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
        padding: 20,
        justifyContent: 'flex-end',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 5,
    },
    heroContent: {
        marginBottom: 20,
    },
    heroTitle: {
        fontSize: 32,
        fontWeight: 'bold',
        color: '#FFFFFF',
        marginBottom: 8,
    },
    heroSubtitle: {
        fontSize: 16,
        color: '#FFFFFF',
        opacity: 0.9,
    },
    quickActionsContainer: {
        marginTop: -30,
        paddingHorizontal: 20,
        marginBottom: 25,
    },
    quickActionsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    quickActionButton: {
        backgroundColor: colors.card,
        borderRadius: 15,
        padding: 15,
        width: '48%',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        borderWidth: 1,
        borderColor: colors.border,
    },
    quickActionIcon: {
        marginBottom: 8,
    },
    quickActionText: {
        fontSize: 14,
        fontWeight: '600',
        color: colors.text,
        textAlign: 'center',
    },
    sectionContainer: {
        paddingHorizontal: 20,
        marginBottom: 25,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 15,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: colors.text,
    },
    seeAllButton: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    seeAllText: {
        fontSize: 14,
        color: colors.primary,
        marginRight: 4,
    },
    liveStreamCard: {
        backgroundColor: colors.card,
        borderRadius: 20,
        overflow: 'hidden',
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        borderWidth: 1,
        borderColor: colors.border,
    },
    liveStreamThumbnail: {
        width: '100%',
        height: 200,
        backgroundColor: '#000',
    },
    liveStreamInfo: {
        padding: 15,
    },
    liveStreamTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: colors.text,
        marginBottom: 8,
    },
    liveStreamMeta: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    liveIndicator: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FF3B30',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
        marginRight: 10,
    },
    liveText: {
        color: '#FFFFFF',
        fontSize: 12,
        fontWeight: 'bold',
        marginLeft: 4,
    },
    viewerCount: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    viewerText: {
        color: colors.text,
        opacity: 0.7,
        fontSize: 12,
        marginLeft: 4,
    },
    upcomingEventsContainer: {
        marginBottom: 20,
    },
    eventCard: {
        backgroundColor: colors.card,
        borderRadius: 15,
        padding: 15,
        marginBottom: 12,
        flexDirection: 'row',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 2,
        borderWidth: 1,
        borderColor: colors.border,
    },
    eventDate: {
        width: 50,
        height: 50,
        backgroundColor: colors.primary + '15',
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 15,
    },
    eventDay: {
        fontSize: 20,
        fontWeight: 'bold',
        color: colors.primary,
    },
    eventMonth: {
        fontSize: 12,
        color: colors.primary,
        textTransform: 'uppercase',
    },
    eventInfo: {
        flex: 1,
    },
    eventTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.text,
        marginBottom: 4,
    },
    eventTime: {
        fontSize: 14,
        color: colors.text,
        opacity: 0.7,
    },
    locationSection: {
        backgroundColor: colors.card,
        borderRadius: 20,
        padding: 20,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        borderWidth: 1,
        borderColor: colors.border,
    },
    locationHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 15,
    },
    locationTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: colors.text,
        marginLeft: 10,
    },
    locationAddress: {
        fontSize: 15,
        color: colors.text,
        opacity: 0.8,
        marginBottom: 15,
        lineHeight: 22,
    },
    mapButton: {
        backgroundColor: colors.primary,
        borderRadius: 12,
        padding: 12,
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
    },
    mapButtonText: {
        color: '#FFFFFF',
        fontSize: 15,
        fontWeight: '600',
        marginLeft: 8,
    },
    fab: {
        position: 'absolute',
        bottom: 20,
        right: 20,
        backgroundColor: colors.primary,
        width: 56,
        height: 56,
        borderRadius: 28,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 5,
    },
    eventLocation: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 4,
    },
    eventLocationText: {
        fontSize: 12,
        color: colors.text,
        opacity: 0.7,
        marginLeft: 4,
    },
    noEventsContainer: {
        padding: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },
    noEventsText: {
        fontSize: 14,
        color: colors.text,
        opacity: 0.7,
        textAlign: 'center',
    },
});

/**
 * Creates themed styles for the WhoWeAre component
 */
export const createWhoWeAreStyles = (colors: any) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.background,
    },
    scrollView: {
        flex: 1,
    },
    scrollViewContent: {
        paddingBottom: 30,
    },
    heroSection: {
        height: 200,
        backgroundColor: colors.primary,
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
        padding: 20,
        justifyContent: 'flex-end',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 5,
    },
    heroContent: {
        marginBottom: 20,
    },
    heroTitle: {
        fontSize: 32,
        fontWeight: 'bold',
        color: '#FFFFFF',
        marginBottom: 8,
    },
    heroSubtitle: {
        fontSize: 16,
        color: '#FFFFFF',
        opacity: 0.9,
    },
    sectionsContainer: {
        padding: 20,
    },
    sectionCard: {
        backgroundColor: colors.card,
        borderRadius: 20,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        borderColor: colors.border,
        borderWidth: 1,
        overflow: 'hidden',
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        backgroundColor: colors.primary + '10',
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    sectionIconContainer: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: colors.text,
        flex: 1,
    },
    sectionContent: {
        padding: 16,
    },
    paragraph: {
        fontSize: 16,
        color: colors.text,
        opacity: 0.8,
        lineHeight: 24,
        marginBottom: 15,
    },
    link: {
        color: colors.primary,
        textDecorationLine: 'underline',
    },
    valueItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    valueIcon: {
        marginRight: 12,
    },
    valueText: {
        fontSize: 16,
        color: colors.text,
        flex: 1,
    },
    teamGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        padding: 16,
    },
    teamMemberCard: {
        width: (Dimensions.get('window').width - 80) / 2,
        backgroundColor: colors.background,
        borderRadius: 12,
        padding: 12,
        marginBottom: 16,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 2,
        borderColor: colors.border,
        borderWidth: 1,
    },
    teamMemberImage: {
        width: 100,
        height: 100,
        borderRadius: 50,
        marginBottom: 12,
        borderWidth: 3,
        borderColor: colors.primary,
    },
    teamMemberInfo: {
        alignItems: 'center',
    },
    teamMemberName: {
        fontSize: 16,
        fontWeight: 'bold',
        color: colors.text,
        textAlign: 'center',
    },
    teamMemberLastName: {
        fontSize: 14,
        color: colors.text,
        opacity: 0.7,
        textAlign: 'center',
    },
    downloadButton: {
        backgroundColor: colors.primary,
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 25,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        alignSelf: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
        elevation: 3,
    },
    downloadButtonText: {
        color: '#FFFFFF',
        fontSize: 15,
        fontWeight: '600',
    },
    retryButton: {
        marginTop: 20,
        padding: 12,
        backgroundColor: colors.primary,
        borderRadius: 8,
        minWidth: 100,
        alignItems: 'center',
    },
    retryButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
    },
});

/**
 * Creates themed styles for the Events component
 */
export const createEventsStyles = (colors: any) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.background,
    },
    scrollView: {
        flex: 1,
    },
    scrollViewContent: {
        paddingBottom: 30,
    },
    heroSection: {
        height: 200,
        backgroundColor: colors.primary,
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
        padding: 20,
        justifyContent: 'flex-end',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 5,
    },
    heroContent: {
        marginBottom: 20,
    },
    heroTitle: {
        fontSize: 32,
        fontWeight: 'bold',
        color: '#FFFFFF',
        marginBottom: 8,
    },
    heroSubtitle: {
        fontSize: 16,
        color: '#FFFFFF',
        opacity: 0.9,
    },
    quickActionsContainer: {
        marginTop: -30,
        paddingHorizontal: 20,
        marginBottom: 25,
    },
    quickActionsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 16,
    },
    quickActionButton: {
        flex: 1,
        backgroundColor: colors.card,
        borderRadius: 20,
        padding: 20,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
        elevation: 5,
        borderWidth: 1,
        borderColor: colors.border,
    },
    quickActionIcon: {
        marginBottom: 8,
    },
    quickActionText: {
        fontSize: 14,
        fontWeight: '600',
        color: colors.text,
        textAlign: 'center',
    },
    viewContent: {
        paddingHorizontal: 20,
    },
    monthNavigation: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 16,
        backgroundColor: colors.card,
        borderRadius: 15,
        padding: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    monthYearButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.background,
        borderRadius: 10,
        paddingVertical: 8,
        paddingHorizontal: 12,
    },
    monthYearText: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.text,
        marginRight: 8,
    },
    filterBar: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 16,
    },
    filterButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.card,
        borderRadius: 10,
        paddingVertical: 8,
        paddingHorizontal: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    filterButtonText: {
        fontSize: 14,
        color: colors.text,
        marginLeft: 6,
    },
    viewToggle: {
        flexDirection: 'row',
        backgroundColor: colors.card,
        borderRadius: 10,
        padding: 4,
    },
    toggleButton: {
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 8,
    },
    activeToggleButton: {
        backgroundColor: colors.primary,
    },
    toggleButtonText: {
        fontSize: 14,
        color: colors.text,
    },
    activeToggleButtonText: {
        color: '#FFFFFF',
    },
    calendarContainer: {
        backgroundColor: colors.card,
        borderRadius: 20,
        overflow: 'hidden',
        height: 400,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        borderWidth: 1,
        borderColor: colors.border,
    },
    calendar: {
        flex: 1,
    },
    eventCard: {
        backgroundColor: colors.card,
        borderRadius: 15,
        marginBottom: 16,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        borderWidth: 1,
        borderColor: colors.border,
        padding: 16,
    },
    eventContent: {
        flex: 1,
        position: 'relative',
        minHeight: 100,
    },
    dateIconContainer: {
        position: 'absolute',
        top: 0,
        right: 0,
        backgroundColor: colors.primary + '15',
        borderRadius: 10,
        padding: 8,
        alignItems: 'center',
        minWidth: 50,
        zIndex: 1,
    },
    dayNumber: {
        fontSize: 22,
        color: colors.primary,
        fontWeight: 'bold',
        marginBottom: 2,
    },
    monthName: {
        fontSize: 13,
        color: colors.primary,
        fontWeight: '500',
        textTransform: 'uppercase',
    },
    eventHeader: {
        marginBottom: 8,
        paddingRight: 65,
        flex: 1,
    },
    eventTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: colors.text,
        marginBottom: 8,
        lineHeight: 24,
    },
    eventDescription: {
        fontSize: 14,
        color: colors.text,
        lineHeight: 20,
        marginBottom: 12,
        opacity: 0.8,
        paddingRight: 55,
    },
    eventLocation: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
        paddingRight: 55,
    },
    locationText: {
        fontSize: 14,
        color: colors.text,
        marginLeft: 8,
        flex: 1,
    },
    eventActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginTop: 4,
    },
    actionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        width: 36,
        height: 36,
        borderRadius: 18,
    },
    secondaryActionButton: {
        backgroundColor: colors.primary + '15',
    },
    primaryActionButton: {
        backgroundColor: colors.primary,
        flex: 1,
    },
    actionButtonText: {
        marginLeft: 6,
        fontSize: 14,
        fontWeight: '500',
        color: colors.primary,
    },
    primaryActionButtonText: {
        color: '#FFFFFF',
    },
    descriptionModal: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1000,
    },
    descriptionModalContent: {
        backgroundColor: colors.card,
        borderRadius: 12,
        width: '87%',
        padding: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 4,
        borderWidth: 1,
        borderColor: colors.border,
    },
    descriptionModalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
        paddingBottom: 8,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    descriptionModalTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: colors.text,
        flex: 1,
        marginRight: 8,
    },
    modalCloseIconButton: {
        padding: 4,
        backgroundColor: colors.background,
        borderRadius: 12,
        height: 24,
        width: 24,
        alignItems: 'center',
        justifyContent: 'center',
    },
    descriptionModalScrollView: {
        maxHeight: 220,
    },
    modalEventDate: {
        fontSize: 14,
        color: colors.primary,
        marginBottom: 12,
        fontWeight: '500',
    },
    descriptionModalText: {
        fontSize: 16,
        color: colors.text,
        lineHeight: 24,
        marginBottom: 16,
    },
    modalPhotoAttachmentsContainer: {
        marginTop: 6,
        padding: 6,
        backgroundColor: colors.background,
        borderRadius: 6,
        marginBottom: 6,
    },
    modalAttachmentsTitle: {
        fontSize: 12,
        fontWeight: '600',
        color: colors.text,
        marginBottom: 4,
    },
    modalPhotoItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 4,
        borderBottomWidth: 1,
        borderBottomColor: colors.border + '30',
    },
    modalAttachmentText: {
        fontSize: 12,
        marginLeft: 4,
        flex: 1,
    },
    modalButtonsContainer: {
        marginTop: 20,
        flexDirection: 'column',
        width: '100%',
    },
    modalButtonsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
    },
    modalActionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 8,
        borderRadius: 6,
    },
    errorText: {
        fontSize: 16,
        color: '#FF3B30',
    },
    loadingContainer: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    viewModeContainer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: colors.card,
        borderRadius: 8,
        marginHorizontal: 16,
        marginBottom: 16,
    },
    viewModeButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 6,
        backgroundColor: 'transparent',
    },
    activeViewModeButton: {
        backgroundColor: colors.primary,
    },
    viewModeText: {
        fontSize: 14,
        color: colors.text,
        marginLeft: 4,
    },
    activeViewModeText: {
        color: '#FFFFFF',
        fontWeight: '600',
    },
    filterModalContent: {
        backgroundColor: colors.background,
        borderRadius: 20,
        width: '90%',
        maxHeight: '80%',
        padding: 20,
    },
    filterModalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    filterModalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: colors.text,
    },
    closeButton: {
        padding: 4,
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.card,
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 8,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: colors.border,
    },
    searchInput: {
        flex: 1,
        marginLeft: 8,
        fontSize: 16,
        color: colors.text,
        padding: 0,
    },
    filterOptionsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
        marginBottom: 24,
    },
    filterOptionCard: {
        flex: 1,
        minWidth: '45%',
        backgroundColor: colors.card,
        borderRadius: 12,
        padding: 16,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: colors.border,
    },
    activeFilterOptionCard: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
    },
    filterOptionCardText: {
        fontSize: 14,
        color: colors.text,
        marginTop: 8,
        textAlign: 'center',
    },
    activeFilterOptionCardText: {
        color: '#FFFFFF',
    },
    sortOptionsContainer: {
        marginBottom: 24,
    },
    sortButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.card,
        padding: 16,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.border,
    },
    sortButtonText: {
        fontSize: 16,
        color: colors.text,
        marginLeft: 12,
    },
    applyButton: {
        backgroundColor: colors.primary,
        borderRadius: 12,
        padding: 16,
        alignItems: 'center',
    },
    applyButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
    },
    featuredContainer: {
        padding: 16,
    },
    featuredSection: {
        marginBottom: 24,
    },
    featuredHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
        paddingBottom: 8,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    featuredTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: colors.text,
        marginLeft: 8,
    },
    featuredEventCard: {
        backgroundColor: colors.card,
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
        borderColor: colors.border,
        borderWidth: 1,
    },
    featuredEventHeader: {
        flexDirection: 'row',
        marginBottom: 12,
    },
    featuredDateContainer: {
        width: 60,
        height: 60,
        backgroundColor: colors.primary,
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    featuredDateDay: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#FFFFFF',
    },
    featuredDateMonth: {
        fontSize: 14,
        color: '#FFFFFF',
        textTransform: 'uppercase',
    },
    featuredEventInfo: {
        flex: 1,
    },
    featuredEventTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.text,
        marginBottom: 4,
    },
    featuredEventTime: {
        fontSize: 14,
        color: colors.text,
        opacity: 0.7,
        marginBottom: 4,
    },
    featuredEventLocation: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    featuredEventLocationText: {
        fontSize: 14,
        color: colors.text,
        opacity: 0.7,
        marginLeft: 4,
    },
    featuredEventActions: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 12,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: colors.border,
    },
    featuredActionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 6,
        backgroundColor: colors.accent,
    },
    featuredActionText: {
        fontSize: 14,
        color: colors.primary,
        marginLeft: 4,
    },
    periodSelectorContainer: {
        marginBottom: 16,
        backgroundColor: colors.card,
        borderRadius: 12,
        padding: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
        borderColor: colors.border,
        borderWidth: 1,
    },
    periodTypeSelector: {
        flexDirection: 'row',
        marginBottom: 12,
        backgroundColor: colors.background,
        borderRadius: 8,
        padding: 4,
    },
    periodTypeButton: {
        flex: 1,
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 6,
        alignItems: 'center',
    },
    activePeriodTypeButton: {
        backgroundColor: colors.primary,
    },
    periodTypeText: {
        fontSize: 14,
        color: colors.text,
        fontWeight: '500',
    },
    activePeriodTypeText: {
        color: '#FFFFFF',
        fontWeight: '600',
    },
    quickPeriodSelector: {
        flexDirection: 'row',
        paddingVertical: 12,
        paddingHorizontal: 16,
        marginBottom: 16,
    },
    quickPeriodButton: {
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 20,
        backgroundColor: colors.card,
        marginRight: 8,
        borderWidth: 1,
        borderColor: colors.border,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 2,
    },
    activeQuickPeriodButton: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
    },
    quickPeriodText: {
        fontSize: 14,
        color: colors.text,
        fontWeight: '500',
    },
    activeQuickPeriodText: {
        color: '#FFFFFF',
        fontWeight: '600',
    },
    monthSelector: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: 8,
    },
    currentMonthButton: {
        flex: 1,
        alignItems: 'center',
        paddingVertical: 8,
    },
    currentMonthText: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.text,
    },
    monthPickerModal: {
        backgroundColor: colors.card,
        borderRadius: 12,
        padding: 20,
        width: '90%',
        maxHeight: '80%',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    monthPickerHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 15,
        paddingBottom: 15,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    monthPickerTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: colors.text,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    monthPicker: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        backgroundColor: colors.card,
        borderRadius: 8,
        padding: 12,
        marginBottom: 15,
    },
    monthPickerItem: {
        width: '30%',
        paddingVertical: 8,
        marginVertical: 4,
        alignItems: 'center',
        borderRadius: 4,
    },
    monthPickerItemActive: {
        backgroundColor: colors.primary,
    },
    monthPickerText: {
        fontSize: 14,
        color: colors.text,
    },
    monthPickerTextActive: {
        color: '#FFFFFF',
        fontWeight: 'bold',
    },
    noEventsContainer: {
        padding: 20,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.card,
        borderRadius: 15,
        marginVertical: 10,
    },
    noEventsText: {
        fontSize: 16,
        color: colors.text,
        opacity: 0.7,
        textAlign: 'center',
    },
    monthNavigationButton: {
        padding: 8,
        borderRadius: 20,
        backgroundColor: colors.card,
    },
    recurrenceTag: {
        color: colors.primary,
        fontSize: 12,
        marginLeft: 6,
    },
    quickFiltersContainer: {
        marginBottom: 16,
        paddingHorizontal: 20,
    },
    quickFiltersContent: {
        paddingVertical: 8,
    },
    quickFilterChip: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.card,
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
        marginRight: 8,
        borderWidth: 1,
        borderColor: colors.border,
    },
    activeQuickFilterChip: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
    },
    quickFilterText: {
        fontSize: 14,
        color: colors.primary,
        marginLeft: 6,
        fontWeight: '500',
    },
    activeQuickFilterText: {
        color: '#FFFFFF',
    },
    moreFiltersButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.background,
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: colors.border,
    },
    moreFiltersText: {
        fontSize: 14,
        color: colors.primary,
        marginLeft: 6,
        fontWeight: '500',
    },
    filterSectionTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.text,
        marginBottom: 12,
        marginTop: 8,
    },
});

/**
 * Creates themed styles for the GetConnectedContent component
 */
export const createGetConnectedStyles = (colors: any) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.background,
    },
    scrollView: {
        flex: 1,
    },
    scrollViewContent: {
        paddingBottom: 30,
    },
    heroSection: {
        height: 220,
        backgroundColor: colors.primary,
        borderBottomLeftRadius: 35,
        borderBottomRightRadius: 35,
        padding: 24,
        justifyContent: 'flex-end',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
        elevation: 8,
    },
    heroContent: {
        marginBottom: 20,
    },
    heroTitle: {
        fontSize: 36,
        fontWeight: 'bold',
        color: '#FFFFFF',
        marginBottom: 12,
        textShadowColor: 'rgba(0, 0, 0, 0.2)',
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 4,
    },
    heroSubtitle: {
        fontSize: 18,
        color: '#FFFFFF',
        opacity: 0.95,
        lineHeight: 24,
        textShadowColor: 'rgba(0, 0, 0, 0.1)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 2,
    },
    quickActionsContainer: {
        marginTop: -40,
        paddingHorizontal: 20,
        marginBottom: 25,
    },
    quickActionsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 16,
    },
    quickActionButton: {
        flex: 1,
        backgroundColor: colors.card,
        borderRadius: 20,
        padding: 20,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
        elevation: 5,
        borderWidth: 1,
        borderColor: colors.border,
    },
    quickActionIconContainer: {
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: colors.primary + '15',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 16,
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    quickActionText: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.text,
        textAlign: 'center',
        marginTop: 4,
    },
    sectionsContainer: {
        paddingHorizontal: 20,
    },
    sectionCard: {
        backgroundColor: colors.card,
        borderRadius: 20,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.1,
        shadowRadius: 6,
        elevation: 4,
        borderWidth: 1,
        borderColor: colors.border,
        overflow: 'hidden',
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        backgroundColor: colors.primary + '10',
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    sectionIconContainer: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: colors.text,
        flex: 1,
    },
    sectionContent: {
        padding: 16,
    },
    sectionText: {
        fontSize: 16,
        color: colors.text,
        opacity: 0.8,
        lineHeight: 24,
        marginBottom: 16,
    },
    contactGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginHorizontal: -8,
        marginBottom: 16,
    },
    contactButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.background,
        borderRadius: 12,
        padding: 12,
        marginHorizontal: 8,
        marginBottom: 12,
        flex: 1,
        minWidth: '45%',
        borderWidth: 1,
        borderColor: colors.border,
    },
    contactIconContainer: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: colors.primary + '15',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 10,
    },
    contactText: {
        fontSize: 14,
        color: colors.text,
        flex: 1,
    },
    sectionButton: {
        backgroundColor: colors.primary,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 14,
        paddingHorizontal: 20,
        borderRadius: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    dualButtonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 12,
        marginTop: 8,
    },
    dualButton: {
        flex: 1,
        backgroundColor: colors.primary,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 14,
        paddingHorizontal: 16,
        borderRadius: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    sectionButtonIcon: {
        marginRight: 8,
    },
    sectionButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
    },
    loadingContainer: {
        justifyContent: 'center',
        alignItems: 'center',
        flex: 1,
    },
    errorText: {
        fontSize: 16,
        color: '#FF3B30',
        marginBottom: 20,
        textAlign: 'center',
        paddingHorizontal: 24,
    },
    retryButton: {
        backgroundColor: colors.primary,
        paddingVertical: 14,
        paddingHorizontal: 28,
        borderRadius: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.2,
        shadowRadius: 5,
        elevation: 4,
    },
    retryButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
    },
});

/**
 * Creates themed styles for the DonationContent component
 */
export const createDonationStyles = (colors: any) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.background,
    },
    scrollView: {
        flex: 1,
    },
    heroSection: {
        height: 200,
        backgroundColor: colors.primary,
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
        padding: 20,
        justifyContent: 'flex-end',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 5,
    },
    heroContent: {
        marginBottom: 20,
    },
    heroTitle: {
        fontSize: 32,
        fontWeight: 'bold',
        color: '#FFFFFF',
        marginBottom: 8,
    },
    heroSubtitle: {
        fontSize: 16,
        color: '#FFFFFF',
        opacity: 0.9,
    },
    cardContainer: {
        backgroundColor: colors.card,
        borderRadius: 20,
        marginHorizontal: 20,
        marginBottom: 25,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        borderWidth: 1,
        borderColor: colors.border,
        overflow: 'hidden',
    },
    cardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        backgroundColor: colors.primary + '10',
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    cardHeaderIcon: {
        marginRight: 12,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: colors.text,
        flex: 1,
    },
    paragraph: {
        fontSize: 16,
        color: colors.text,
        opacity: 0.8,
        lineHeight: 24,
        padding: 16,
    },
    bankDetailsContainer: {
        marginTop: 16,
        backgroundColor: colors.card,
        padding: 18,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.border,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 2,
        marginHorizontal: 16,
        marginBottom: 16,
    },
    bankDetailRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
        paddingHorizontal: 4,
    },
    bankDetailLabel: {
        fontSize: 14,
        color: colors.text,
        fontWeight: '500',
        opacity: 0.8,
        flex: 1,
        marginRight: 10,
    },
    bankDetailValueContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    bankDetailValue: {
        fontSize: 14,
        color: colors.primary,
        fontWeight: '600',
        marginRight: 8,
        textAlign: 'right',
    },
    donateNowContainer: {
        paddingHorizontal: 16,
        paddingVertical: 24,
        marginTop: 8,
        marginBottom: 16,
    },
    donateNowButton: {
        backgroundColor: colors.primary,
        paddingVertical: 18,
        borderRadius: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.35,
        shadowRadius: 4,
    },
    donateNowButtonText: {
        color: '#fff',
        fontSize: 20,
        fontWeight: 'bold',
    },
    quickActionsContainer: {
        marginTop: -30,
        paddingHorizontal: 20,
        marginBottom: 25,
    },
    quickActionsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    quickActionButton: {
        backgroundColor: colors.card,
        borderRadius: 15,
        padding: 15,
        width: '48%',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        borderWidth: 1,
        borderColor: colors.border,
    },
    quickActionIcon: {
        marginBottom: 8,
    },
    quickActionText: {
        fontSize: 14,
        fontWeight: '600',
        color: colors.text,
        textAlign: 'center',
    },
    fab: {
        position: 'absolute',
        bottom: 20,
        right: 20,
        backgroundColor: colors.primary,
        width: 56,
        height: 56,
        borderRadius: 28,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 5,
    },
});